### ISSUE TITLE
Territory is not reloaded if you write the command from the console to reload the territory

### ISSUE THREAD

**Issue by moderator10000078** [Hetag1216/AreaReloader-FAWE#4]
rather unpleasant bug

**Comment by Hetag1216** [comment]
Thanks for the report!
Would you be able to provide further details by enablind the debug option and try to load the area via console once again?
Once done please attach the debug.txt file so that I may further investigate on the issue, thanks in advance!

**Comment by Hetag1216** [comment]
Fixed incorrect casting of sender upon event call that was causing the areas not to load upon running the command via console.
ec6435c
